spring.application.name=finance-backend

#Application server port
server.port=8080



#Mysql Connection

spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=rootuser99
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Jwt secret key
jwt.secret=7f9c2ba4d8e5f1a6b3c9d2e7f4a8b1c6d9e3f7a2b5c8e1d4f6a9c2b7e5d8f1a3







